
namespace SMBLibrary.SMB2
{
    public enum NegotiateContextType : ushort
    {
        SMB2_PREAUTH_INTEGRITY_CAPABILITIES = 0x0001,
        SMB2_ENCRYPTION_CAPABILITIES = 0x0002,
        SMB2_COMPRESSION_CAPABILITIES = 0x0003,
        SMB2_NETNAME_NEGOTIATE_CONTEXT_ID = 0x0005,
        SMB2_TRANSPORT_CAPABILITIES = 0x0006,
        SMB2_RDMA_TRANSFORM_CAPABILITIES = 0x0007,
        SMB2_SIGNING_CAPABILITIES = 0x0008,
    }
}
